title: <p align="center"> Giorgi Gelovani </p>

logo: "/images/index2.png"

description:
  <p align="center">
  <a href="FR_Giorgi_GELOVANI.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/giorgge/">LinkedIn</a> |
  <a href="https://github.com/GioFr">GitHub</a>
  </p>
  
  <p align="justify">
  Hi, my name is Giorgi. I am a masters gradute from Ecole Centrale de Nantes in Signal and Image Processing.
  I am an AI enthusiast and I am very passionate about science and technology. 
  <br><br>
  Welcome to my page where I demosntrate some of the projects I have been working on.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
