title: <p align="center"> Giorgi Gelovani </p>

logo: "/images/index2.jpg"

description:
  <p align="center">
  <a href="/FR_Giorgi_GELOVANI.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/giorgge/">LinkedIn</a> |
  <a href="https://github.com/GioFr">GitHub</a>
  </p>
  
  <p align="justify">
  Hi, my name is Giorgi. I am an AI enthusiast and I am very passionate about science and technology. 
  I am specialized in Signal and Image Processing and my major interest is working on task related to AI.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
