title: Giorgi Gelovani
logo: "images/index2.jpg"
description: 
  About Me
  Hi, my name is Giorgi. I am a AI enthusiast and I am very passionate about science and technology. 
  I am specialized in Signal and Image Processing and my major interest is working on task related to AI.
theme: jekyll-theme-minimal
