title: <p align="center"> Giorgi Gelovani </p>

logo: "/images/index2.png"

description:
  <p align="center">
  <a href="FR_Giorgi_GELOVANI.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/giorgge/">LinkedIn</a> |
  <a href="https://github.com/GioFr">GitHub</a>
  </p>
  
  <p align="justify">
  Hi, my name is Giorgi(25 yo). I am a masters graduate from Ecole Centrale de Nantes specialised in Signal and Image Processing.
  <br><br>
  I am an AI enthusiast and I am very passionate about science & technology.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
